TRAIN:
 batch_size: 64
 lr_1: 1e-5
 lr_diff: 1e-5
 lr_finetune: 1e-5
 epochs_phase1: 20
 epochs_phase2: 0
 num_unfrozen1: 5
 num_unfrozen2: 0
 wd1: 2e-4
 wd2: 2e-4
 num_steplr: 100
 classe_weights: false
 label_smoothing: 0
 input_size: 384
 scheduler1: warm_cosine
 scheduler_diff: warm_cosine
 scheduler2: steplr
 milestones: [30,70]
 model_name: "models/efficientnet_weights.pth"
 activation: nn.SiLU
 optimizer: 'adamw'
 beta1: 0.9
 beta2: 0.9999
 t0: 7
 t_mult: 1
